name: Test Coverage

on: [ push, pull_request ]

jobs:
  build:
    name: Code-Coverage

    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # 2.3.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            codecov.io:443
            github.com:443
            registry.npmjs.org:443
            registry.yarnpkg.com:443
            storage.googleapis.com:443
            uploader.codecov.io:443

      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # 3.5.0

      - name: Install Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # 3.6.0
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests with coverage
        run: yarn test-coverage

      - uses: codecov/codecov-action@40a12dcee2df644d47232dde008099a3e9e4f865 # 3.1.2
        with:
          directory: ./coverage/
