name: Test Coverage

on: [ push, pull_request ]

jobs:
  build:
    name: Code-Coverage

    runs-on: ubuntu-latest

    steps:
      - uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # 2.5.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            codecov.io:443
            github.com:443
            registry.npmjs.org:443
            registry.yarnpkg.com:443
            storage.googleapis.com:443
            uploader.codecov.io:443

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # 3.5.3

      - name: Install Node
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # 3.7.0
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests with coverage
        run: yarn test-coverage

      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # 3.1.4
        with:
          directory: ./coverage/
